# -*- coding: utf-8 -*-
"""Demand Forecasting and Inventory Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gQfdLOjOS0-iFVliVTdpUH83KZgNCg4
"""

import pandas as pd
import numpy as np
import plotly.express as px
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

data = pd.read_csv("demand_inventory.csv")
print(data.head())

data = data.drop(columns=['Unnamed: 0'])

fig_demand = px.line(data, x='Date',
                     y='Demand',
                     title='Demand Over Time')
fig_demand.show()

fig_inventory = px.line(data, x='Date',
                        y='Inventory',
                        title='Inventory Over Time')
fig_inventory.show()

data['Date'] = pd.to_datetime(data['Date'], format='%Y-%m-%d') # Changed the format to '%Y-%m-%d' to match the date format in the data.
time_series = data.set_index('Date')['Demand']

differenced_series = time_series.diff().dropna()

# Plot ACF and PACF of differenced time series
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
plot_acf(differenced_series, ax=axes[0])
plot_pacf(differenced_series, ax=axes[1])
plt.show()

order = (1, 1, 1)
seasonal_order = (1, 1, 1, 2) #2 because the data contains a time period of 2 months only
model = SARIMAX(time_series, order=order, seasonal_order=seasonal_order)
model_fit = model.fit(disp=False)

future_steps = 10
predictions = model_fit.predict(len(time_series), len(time_series) + future_steps - 1)
predictions = predictions.astype(int)
print(predictions)

# Create date indices for the future predictions
future_dates = pd.date_range(start=time_series.index[-1] + pd.DateOffset(days=1), periods=future_steps, freq='D')

# Create a pandas Series with the predicted values and date indices
forecasted_demand = pd.Series(predictions, index=future_dates)

# Initial inventory level
initial_inventory = 5500

# Lead time (number of days it takes to replenish inventory)
lead_time = 1 # it's different for every business, 1 is an example

# Service level (probability of not stocking out)
service_level = 0.95 # it's different for every business, 0.95 is an example

# Calculate the optimal order quantity using the Newsvendor formula
z = np.abs(np.percentile(forecasted_demand, 100 * (1 - service_level)))
order_quantity = np.ceil(forecasted_demand.mean() + z).astype(int)

# Calculate the reorder point
reorder_point = forecasted_demand.mean() * lead_time + z

# Calculate the optimal safety stock
safety_stock = reorder_point - forecasted_demand.mean() * lead_time

# Calculate the total cost (holding cost + stockout cost)
holding_cost = 0.1  # it's different for every business, 0.1 is an example
stockout_cost = 10  # # it's different for every business, 10 is an example
total_holding_cost = holding_cost * (initial_inventory + 0.5 * order_quantity)
total_stockout_cost = stockout_cost * np.maximum(0, forecasted_demand.mean() * lead_time - initial_inventory)

# Calculate the total cost
total_cost = total_holding_cost + total_stockout_cost

print("Optimal Order Quantity:", order_quantity)
print("Reorder Point:", reorder_point)
print("Safety Stock:", safety_stock)
print("Total Cost:", total_cost)

! pip install streamlit

# Save this file as app.py and run it using: streamlit run app.py

import streamlit as st
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
import plotly.express as px
import matplotlib.pyplot as plt

st.set_page_config(page_title="Demand Forecasting App", layout="centered")

st.title("📦 Demand Forecasting & Inventory Optimization")

# Upload CSV file
uploaded_file = st.file_uploader("Upload your CSV file", type=["csv"])
if uploaded_file:
    data = pd.read_csv(uploaded_file)

    # Basic checks and conversion
    if 'Date' in data.columns and 'Demand' in data.columns:
        data['Date'] = pd.to_datetime(data['Date'])
        data.sort_values('Date', inplace=True)
        data.set_index('Date', inplace=True)

        st.subheader("📊 Data Preview")
        st.write(data.head())

        st.subheader("📈 Demand Over Time")
        fig_demand = px.line(data, x=data.index, y='Demand', title='Demand Trend')
        st.plotly_chart(fig_demand)

        if 'Inventory' in data.columns:
            st.subheader("📦 Inventory Over Time")
            fig_inventory = px.line(data, x=data.index, y='Inventory', title='Inventory Trend')
            st.plotly_chart(fig_inventory)

        st.sidebar.header("🔧 SARIMAX Model Parameters")
        p = st.sidebar.slider("AR (p)", 0, 5, 1)
        d = st.sidebar.slider("Differencing (d)", 0, 2, 1)
        q = st.sidebar.slider("MA (q)", 0, 5, 1)

        seasonal = st.sidebar.checkbox("Use Seasonal Component", value=True)
        if seasonal:
            P = st.sidebar.slider("Seasonal AR (P)", 0, 2, 1)
            D = st.sidebar.slider("Seasonal Differencing (D)", 0, 1, 1)
            Q = st.sidebar.slider("Seasonal MA (Q)", 0, 2, 1)
            s = st.sidebar.slider("Seasonal Period (s)", 1, 30, 7)
        else:
            P = D = Q = s = 0

        future_steps = st.sidebar.number_input("Forecast Steps (Days)", min_value=1, max_value=30, value=10)

        if st.button("🔮 Run Forecast"):
            model = SARIMAX(data['Demand'],
                            order=(p, d, q),
                            seasonal_order=(P, D, Q, s) if seasonal else (0, 0, 0, 0))
            model_fit = model.fit(disp=False)

            forecast = model_fit.forecast(steps=future_steps)
            forecast_dates = pd.date_range(start=data.index[-1] + pd.DateOffset(days=1), periods=future_steps)
            forecast_series = pd.Series(forecast.values, index=forecast_dates)

            st.subheader("📅 Forecasted Demand")
            st.line_chart(forecast_series)

            st.write("Forecasted values:")
            st.dataframe(forecast_series.rename("Predicted Demand"))
    else:
        st.warning("CSV must include 'Date' and 'Demand' columns.")

from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv("demand_inventory.csv")
data['Date'] = pd.to_datetime(data['Date'])

forecast_days = 10

for pid in data['Product_ID'].unique():
    df = data[data['Product_ID'] == pid].copy()
    df = df.sort_values('Date').set_index('Date')
    ts = df['Demand']

    model = SARIMAX(ts, order=(1, 1, 1), seasonal_order=(1, 1, 1, 7))
    model_fit = model.fit(disp=False)
    forecast = model_fit.forecast(steps=forecast_days)

    forecast.index = pd.date_range(start=ts.index[-1] + pd.Timedelta(days=1), periods=forecast_days)

    plt.figure(figsize=(8, 4))
    plt.plot(ts, label="Historical Demand")
    plt.plot(forecast, label="Forecast", linestyle='--')
    plt.title(f"Product {pid} Forecast")
    plt.legend()
    plt.show()

data['Date'] = pd.to_datetime(data['Date'])
data['DayOfWeek'] = data['Date'].dt.dayofweek
data['Month'] = data['Date'].dt.month
data['IsWeekend'] = data['DayOfWeek'].isin([5, 6]).astype(int)

import numpy as np

# Randomly assign categories
np.random.seed(0)
product_ids = data['Product_ID'].unique()
categories = ['Perishable', 'Non-Perishable']
class_map = {pid: np.random.choice(categories) for pid in product_ids}
data['Category'] = data['Product_ID'].map(class_map)

def simulate_inventory_policy(demand, reorder_point, order_qty, init_inv=1000):
    inventory = init_inv
    stockouts = 0
    for d in demand:
        if inventory < d:
            stockouts += 1
        inventory -= d
        if inventory <= reorder_point:
            inventory += order_qty
    return stockouts

product = 'A1001'
df = data[data['Product_ID'] == product].sort_values('Date')
demand_series = df['Demand'].values

policy_A = simulate_inventory_policy(demand_series, reorder_point=300, order_qty=500)
policy_B = simulate_inventory_policy(demand_series, reorder_point=500, order_qty=500)

print("Policy A Stockouts:", policy_A)
print("Policy B Stockouts:", policy_B)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Ensure that 'product' is a valid Product_ID present in your data
product = data['Product_ID'].unique()[0]  # Choose the first unique Product_ID as an example

df = data[data['Product_ID'] == product].sort_values('Date')
df['Lag1'] = df['Demand'].shift(1)
# Instead of dropping all rows with NaN, fill with the mean
# This will preserve data points even after the shift
df['Lag1'] = df['Lag1'].fillna(df['Lag1'].mean())

X = df[['Lag1']]
y = df['Demand']
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False)

model = RandomForestRegressor().fit(X_train, y_train)
y_pred = model.predict(X_test)

print("ML Predicted Demand (RandomForest):", y_pred[:5])

from sklearn.metrics import mean_squared_error, mean_absolute_error

metrics = []
forecast_days = 10

for pid in data['Product_ID'].unique():
    df = data[data['Product_ID'] == pid].sort_values('Date')
    df.set_index('Date', inplace=True)
    ts = df['Demand']

    train = ts[:-forecast_days]
    test = ts[-forecast_days:]

    model = SARIMAX(train, order=(1,1,1), seasonal_order=(1,1,1,7))
    model_fit = model.fit(disp=False)
    pred = model_fit.forecast(steps=forecast_days)

    # Calculate RMSE without the 'squared' argument and take the square root if necessary
    rmse = np.sqrt(mean_squared_error(test, pred))

    mae = mean_absolute_error(test, pred)
    mape = np.mean(np.abs((test - pred) / test)) * 100

    metrics.append({"Product_ID": pid, "RMSE": rmse, "MAE": mae, "MAPE": mape})

print(pd.DataFrame(metrics))

def simulate_stock_behavior(demand_series, inventory=1000, reorder_point=400, order_qty=600):
    stockouts = 0
    overstock_days = 0
    daily_inventory = []

    for demand in demand_series:
        if inventory < demand:
            stockouts += 1
        inventory -= demand
        if inventory <= reorder_point:
            inventory += order_qty
        if inventory > 1500:  # Threshold for overstock
            overstock_days += 1
        daily_inventory.append(inventory)

    return stockouts, overstock_days, daily_inventory

df = data[data['Product_ID'] == product].sort_values('Date')
stockouts, overstock_days, inventory_trace = simulate_stock_behavior(df['Demand'])

plt.plot(df['Date'], inventory_trace)
plt.title(f"Inventory Behavior for {product}")
plt.xlabel("Date")
plt.ylabel("Inventory Level")
plt.grid(True)
plt.show()

print("Total Stockouts:", stockouts)
print("Overstock Days:", overstock_days)